### ISSUE TITLE
WebDriver获取失败

### ISSUE THREAD

**Issue by zhaichanghui27** [jklincn/PaperDownloader#2]
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1921, in __call__
  File "gui.py", line 147, in bf_get_driver
  File "driver_helper.py", line 67, in get_driver
  File "driver_helper.py", line 36, in chrome
PermissionError: [Errno 13] Permission denied: 'chromedriver-win64.zip'

**Comment by jklincn** [comment]
您好，我猜测是工作目录的问题。我增加了一些调试信息来更好地找到问题所在。

- 如果您使用的是exe文件，请下载 [v1.1.1](https://github.com/jklincn/PaperDownloader/releases/download/v1.1.1/PaperDownloader.exe) 再尝试一下。
- 如果您使用的是源代码运行，请拉取 [issues#2](https://github.com/jklincn/PaperDownloader/tree/issues%232) 分支再尝试一下

**Comment by zhaichanghui27** [comment]
非常感谢您的回复





------------------ 原始邮件 ------------------
发件人: jklincn ***@***.***&gt;
发送时间: 2023年11月11日 11:42
收件人: jklincn/PaperDownloader ***@***.***&gt;
抄送: 翟常辉 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [jklincn/PaperDownloader] WebDriver获取失败 (Issue #2)





 
您好，我猜测是工作目录的问题。我增加了一些调试信息来更好地找到问题所在。
  
如果您使用的是exe文件，请下载 v1.1.1 再尝试一下。
 
如果您使用的是源代码运行，请拉取 issues#2 分支再尝试一下
