### ISSUE TITLE
较多下载后会要求滑块验证码，是否设置了足够睡眠时间？

### ISSUE THREAD

**Issue by Alex-SYZ1** [jklincn/PaperDownloader#3]
<img width="928" alt="28f404af0cda1fd0362393fe34ebc92" src="https://github.com/jklincn/PaperDownloader/assets/117272700/b53d7ec7-ed44-4ad5-b89f-e1b9ce4e324b">

**Comment by jklincn** [comment]
默认的下载间隔时间为 3 秒，可在 config.py 中修改。后续我有时间的话可以加上对滑块验证码的自动处理

**Comment by jklincn** [comment]
目前已经完成知网滑块验证码的自动处理。 commit efcbde4

**Comment by Alex-SYZ1** [comment]
👍👍🏻👍🏼👍🏽👍🏾👍🏿点赞，之后仔细拜读你的代码
之前贵仓库的代码我仔细学习了，尤其是自动检测浏览器版本、下载对应驱动，降低了代码使用门槛，极其受触动，点赞

**Comment by jklincn** [comment]
自动下载驱动这事其实很多人在做，比如 [https://github.com/bonigarcia/webdrivermanager](https://github.com/bonigarcia/webdrivermanager)，但当时我引入的时候发现效果不好（有错误）。selenium 官方也有自己的 Selenium Manager，可以完成浏览器和驱动的自动管理，但有些复杂，加上网络原因也不太好用。所以自己写了一个简单的下载脚本。

“拜读”太客气了，我的代码水平也一般，互相交流学习吧。
