### ISSUE TITLE
请问为什么出现元素遮挡

### ISSUE THREAD

**Issue by rfgddd** [jklincn/PaperDownloader#5]
Message: element click intercepted: Element <a onclick="WriteKrsDownLog()" target="_blank" id="pdfDown" name="pdfDown" href="https://bar.cnki.net/bar/download/order?id=Pmp%2F5es3RB81cmauPwpbvjMKNSQwBIl4wRdJzL0QEWzXcAnP8r1CXQr3sOk9lHqSMLy%2B8buQaKxWH13vOikKN0zDNVPVjsud6rmLrTRk%2B5kYz7hIz%2Bm4gioz%2Fd0uFLWAKNpqZ87Xp6tkLK6WMt2WIyBnBa%2BGi6z13JPvtSv3a9ygQ3rcCWK8v00%2FaZoGrk3nC2zA6570xka5nDCp1DiyfdfkBoVMq5pdIlX9W2etNuw%3D">...</a> is not clickable at point (662, 605). Other element would receive the click: <div class="doc">...</div>

**Comment by jklincn** [comment]
能提供具体的复现流程吗？

**Comment by rfgddd** [comment]
> 能提供具体的复现流程吗？
使用jupyter运行的，其他没有更改
![屏幕截图_16-7-2024_101620_localhost](https://github.com/user-attachments/assets/3e1167e6-0b85-441e-b21e-e0fb7d078fee)

**Comment by jklincn** [comment]
我刚刚本地试了下，chrome+知网是正常下载的。这个问题是稳定复现吗？或者试一下用 python 直接运行而不是使用 jupyter

**Comment by rfgddd** [comment]
> 我刚刚本地试了下，chrome+知网是正常下载的。这个问题是稳定复现吗？或者试一下用 python 直接运行而不是使用 jupyter

好像是只能下载仅有pdf的论文，如果论文有html会遮挡
<img width="441" alt="219720bb3ecdf88fbde7ccf766cba7a" src="https://github.com/user-attachments/assets/f1a789df-f2bc-4afc-b582-07016893a3a7">
![e168ff3b8f90e5a96b7686cb6220050](https://github.com/user-attachments/assets/cb1d41a4-ea09-4006-8e11-e37068ba3b70)

**Comment by rfgddd** [comment]
> 我刚刚本地试了下，chrome+知网是正常下载的。这个问题是稳定复现吗？或者试一下用 python 直接运行而不是使用 jupyter

我用的是Edge，用chrome登不上知网，开vpn登上的是英文页面的

**Comment by jklincn** [comment]
你好，我在本地使用 edge+知网根据你描述的尝试了一下，如果论文详情页存在 HTML 阅读标签的话，是不影响下载的。你这边的环境可以发一下吗？

我的本地环境：
- Python 3.11.5
- selenium 4.18.1
- Microsoft Edge 126.0.2592.102

**Comment by rfgddd** [comment]
> 你好，我在本地使用 edge+知网根据你描述的尝试了一下，如果论文详情页存在 HTML 阅读标签的话，是不影响下载的。你这边的环境可以发一下吗？
> 
> 我的本地环境：
> 
> * Python 3.11.5
> * selenium 4.18.1
> * Microsoft Edge 126.0.2592.102

解决了！是selenium版本的问题，非常感谢jk老师
<img width="75" alt="70330f5aff0986ea74de0b37c80ccb7" src="https://github.com/user-attachments/assets/a9e29a2e-112b-4dcf-9cba-64918b538335">

**Comment by jklincn** [comment]
祝贺！
