### ISSUE TITLE
万方的学位论文下载不成功

### ISSUE THREAD

**Issue by yzl256** [jklincn/PaperDownloader#8]
请登录数据库网站进行内容检索, 在需要下载的论文前面打上勾，完成后输入回车键开始下载
=======================================
正在接管浏览器控制，请不要操作。
检测到万方检索页面, 开始下载......
已经下载了1篇文献
错误：不能下载 供应链中不同标注信息的包容性研究。

错误：不能下载 基于大数据技术的电商企业供应链成本控制研究--以京东商城为例。

错误：不能下载 国际贸易大宗物资供应链融资模式研究——以铁矿石进口为例。

错误：不能下载 数字化供应链下海康威视营运资金管理绩效研究。

错误：不能下载 考虑主播类型的直播电商供应链运营策略研究。

错误：不能下载 供应链视角下电商企业物流成本控制研究--以京东为例。

错误：不能下载 YL公司基于区块链的供应链金融信息共享策 略优化研究。

错误：不能下载 基于区块链的生鲜农产品供应链系统研究。

错误：不能下载 基于供应链的A零售企业营运资金管理研究。

错误：不能下载 物流企业供应链金融效果分析--以顺丰控股为例。

错误：不能下载 新能源汽车行业核心企业供应链融资的动因及效果分析--以比亚迪公司为例。

错误：不能下载 供应链关系质量、组织韧性与制造企业竞争优势的关系研究。

错误：不能下载 大数据背景下供应链成本管理分析--以海尔智家为例。

错误：不能下载 我国石化企业绿色供应链运营绩效评价研究。

错误：不能下载 九州通供应链数字化转型的动因及绩效研究。

错误：不能下载 碳限额机制下纺织服装闭环供应链运作决策研究。

错误：不能下载 供应链票据在绿色供应链融资中的应用研究--以TCL“绿色碳链通”为例。

错误：不能下载 “区块链+供应链金融”运作模式和效果研究--以比亚迪“迪链”供应链金融为例。

错误：不能下载 数字化转型下海尔智家供应链成本管理实施效果评价。

下载完成, 共找到 20 处勾选, 成功下载 1 项内容。

**Comment by jklincn** [comment]
看起来程序是工作正常的。你的账号有这些论文的下载权限吗？手动下载其中几篇试试看？

我尝试了一下，搜索关键词是“供应链”，筛选出学位论文，《基于大数据技术的电商企业供应链成本控制研究--以京东商城为例》这篇是可以正常自动下载的。

**Comment by yzl256** [comment]
手动是可以下载的，说明我的账号是有这些论文的下载权限的，但不知为何下载失败

**Comment by jklincn** [comment]
我现在没法复现，你可以复现一下然后录屏发送到我的邮箱 jklincn@outlook.com 。或者使用详细的文字和图片说明能让我成功复现问题。

**Comment by jklincn** [comment]
长时间未回复，关闭
